#if !defined( STRINGS_H )
#define STRINGS_H

#define STR_WIN_WINDOWTITLE                        "Open GL Game"

#define STR_WINERR_HEADER                          "Windows Error"
#define STR_WINERR_PERFORMANCEFREQUENCY            "Failed to query performance frequency."
#define STR_WINERR_TIMERRESOLUTION                 "Failed to set timer resolution."
#define STR_WINERR_REGISTERWINDOW                  "Failed to register main window class."
#define STR_WINERR_CREATEWINDOW                    "Failed to create main window."
#define STR_WINERR_CLIENTRECT                      "Failed to get window client rect."
#define STR_WINERR_NOPIXELFORMAT                   "No OpenGL pixel formats available."
#define STR_WINERR_UNSUITABLEPIXELFORMAT           "No suitable OpenGL pixel format found."
#define STR_WINERR_RENDERINGCONTEXT                "Failed to make OpenGL rendering context current."
#define STR_WINERR_ADJUSTCLIENTRECT                "Failed to adjust the main window client size."
#define STR_WINERR_LOGMESSAGE                      "Windows error: %s"
#define STR_WINERR_APPDIRECTORY                    "Failed to get the app's base directory."
#define STR_WINERR_INITGAME                        "Failed to initialize game."
#define STR_WINERR_CREATELOGFILE                   "Failed to open log file."
#define STR_WINERR_WRITELOGFILE                    "Failed to write message to log file."
#define STR_WINERR_INITTHREADS                     "Failed to initialize threads."

#define STR_FILEERR_OPENFILEFAILED                 "File error: could not open file: %s"
#define STR_FILEERR_GETFILESIZEFAILED              "File error: could not get file size: %s"

#define STR_BMPERR_MEMORYCORRUPT                   "BMP error: bitmap memory is corrupt, image ID %u"
#define STR_BMPERR_INVALIDHEADERTYPE               "BMP error: invalid header type, only BM is allowed, image ID %u"
#define STR_BMPERR_HEADERCORRUPT                   "BMP error: header section is corrupt, image ID %u"
#define STR_BMPERR_INVALIDDIBHEADERTYPE            "BMP error: invalid DIB header type, on BITMAPINFOHEADER is allowed, image ID %u"
#define STR_BMPERR_INVALIDCOLORPLANES              "BMP error: invalid number of color planes, image ID %u"
#define STR_BMPERR_INVALIDBPP                      "BMP error: invalid number of bits per pixel, image ID %u"
#define STR_BMPERR_ISCOMPRESSED                    "BMP error: compression is not currently supported, image ID %u"
#define STR_BMPERR_INVALIDIMAGESIZE                "BMP error: invalid image size, image ID %u"
#define STR_BMPERR_INVALIDPALETTECOUNT             "BMP error: invalid number of palette colors, image ID %u"
#define STR_BMPERR_PALETTECORRUPT                  "BMP error: palette is corrupt, image ID %u"
#define STR_BMPERR_INVALIDCOLORINDEXING            "BMP error: color indexing is not currently supported, image ID %u"

#define STR_GDFERR_FILECORRUPT                     "Game data file error: file is corrupt: %s"
#define STR_GDFERR_NOCHUNKSFOUNDFORID              "Game data file error: no chunks found for chunk ID: %u"
#define STR_GDFERR_SPRITEBASECORRUPT               "Game data file error: sprite base memory is corrupt, sprite base ID %u"
#define STR_GDFERR_SPRITEBASEIMAGENOTFOUND         "Game data file error: sprite base image ID not found: %u"
#define STR_GDFERR_SPRITECORRUPT                   "Game data file error: sprite memory is corrupt, sprite ID %u"
#define STR_GDFERR_SPRITEBASENOTFOUND              "Game data file error: sprite base ID not found: %u"
#define STR_GDFWARN_UNKNOWNCHUNKID                 "Game data file warning: unknown chunk ID encountered: %u"
#define STR_GDFWARN_UNKNOWNBITMAPENTRYID           "Game data file warning: unknown bitmap entry ID encountered: %u"
#define STR_GDFWARN_UNKNOWNFONTENTRYID             "Game data file warning: unknown font entry ID encountered: %u"
#define STR_GDFWARN_UNKNOWNSPRITEBASEID            "Game data file warning: unknown sprite base ID encountered: %u"
#define STR_GDFWARN_UNKNOWNSPRITEID                "Game data file warning: unknown sprite ID encountered: %u"

#define STR_SPRITEERR_FRAMEDIMENSIONS              "Sprite error: frame dimensions don't match texture, image ID %u"
#define STR_SPRITEERR_MEMORYCORRUPT                "Sprite error: sprite memory is corrupt, sprite base ID %u"

#define STR_FONTERR_MEMORYCORRUPT                  "Font error: font memory is corrupt, font ID %u"

#define STR_WADERR_FILEOPEN                        "WAD file error: failed to open file: %s"
#define STR_WADERR_TEXTURETABLEINDEXRANGE          "WAD file error: texture table index %d patch ID %d is out of range"
#define STR_WADERR_FILESIZEHEADER                  "WAD file error: file is too small to contain a header"
#define STR_WADERR_WADTYPE                         "WAD file error: file is neither an IWAD or PWAD type"
#define STR_WADERR_LUMPCOUNTNEGATIVE               "WAD file error: lump count must be greater than zero"
#define STR_WADERR_LUMPTABLEOFFSET                 "WAD file error: lump info table offset must be greater than zero"
#define STR_WADERR_LUMPTABLESIZE                   "WAD file error: lump info table is too large"
#define STR_WADERR_LUMPPOSITIONNEGATIVE            "WAD file error: lump number %d file position cannot be less than zero"
#define STR_WADERR_LUMPNUMBERNEGATIVE              "WAD file error: lump number %d size cannot be less than zero"
#define STR_WADERR_LUMPNUMBERLENGTH                "WAD file error: lump number %d has exceeded the size of the file"
#define STR_WADERR_LUMPNUMBERSIZE                  "WAD file error: lump number %d (%s) is too large"
#define STR_WADERR_MULTIPLEPALETTES                "WAD file error: file cannot contain multiple palette lumps"
#define STR_WADERR_PALETTESIZE                     "WAD file error: palette size is invalid"
#define STR_WADERR_TEXTURELUMPSIZEHEADER           "WAD file error: texture lump size is too small for texture headers"
#define STR_WADERR_TEXTURECOUNTZERO                "WAD file error: texture lump must contain at least one texture"
#define STR_WADERR_TEXTURELUMPSIZE                 "WAD file error: texture lump size is too small for all defined textures"
#define STR_WADERR_TEXTUREOFFSET                   "WAD file error: texture offset is invalid"
#define STR_WADERR_TEXTUREPATCHCOUNTZERO           "WAD file error: texture must contain at least one patch"
#define STR_WADERR_TEXTUREPATCHOVERFLOW            "WAD file error: file contains too many texture patches"
#define STR_WADERR_MULTIPLETEXTUREPATCHNAMES       "WAD file error: file cannot contain multiple texture patch name lumps"
#define STR_WADERR_TEXTUREPATCHNAMECOUNTZERO       "WAD file error: file must have at least one texture patch name"
#define STR_WADERR_TEXTUREPATCHNAMEOVERFLOW        "WAD file error: file contains too many texture patch names"
#define STR_WADERR_PREMATUREPATCHTABLE             "WAD file error: file must define texture patch names before the patch table"
#define STR_WADERR_TEXTUREPATCHTABLESHORT          "WAD file error: texture patch table ended prematurely"
#define STR_WADERR_TEXTUREPATCHREADZERO            "WAD file error: file does not contain any texture patches"
#define STR_WADERR_PATCHTABLEOVERFLOW              "WAD file error: patch table is too long"
#define STR_WADERR_PATCHOVERFLOW                   "WAD file error: texture patch %s is too large"
#define STR_WADERR_PATCHCOUNTOVERFLOW              "WAD file error: file contains too many texture patches"
#define STR_WADERR_FLATTABLEOVERFLOW               "WAD file error: flat texture table is too large"
#define STR_WADERR_FLATTABLECOUNTZERO              "WAD file error: flat table has no entries"
#define STR_WADERR_FLATLUMP_OVERFLOW               "WAD file error: flat texture lump %s is too large"

#define STR_WADWARN_INVALIDTEXTUREPATCHLUMP        "WAD file warning: file contains invalid lump (%s) inside texture patch table"
#define STR_WADWARN_UNDEFINEDTEXTUREPATCHLOADED    "WAD file warning: texture patch %s was not defined in patch names, but was still added to patch table"
#define STR_WADWARN_DEFINEDTEXTUREPATCHNOTLOADED   "WAD file warning: texture patch %s was defined but not loaded"
#define STR_WADWARN_FLATNOTLOADED                  "WAD file warning: flat texture number %d was not loaded"

#define STR_WADINFO_PATCHOVERWRITTEN               "WAD file info: texture patch %s was overwritten by another texture patch with the same name"

#define STR_DIAG_FRAMETARGETMICRO                  "Target frame microseconds: %lld"
#define STR_DIAG_FRAMEDURATIONMICRO                "Last frame microseconds: %lld"
#define STR_DIAG_LAGFRAMES                         "Lag frames: %u"
#define STR_DIAG_THREADCOUNT                       "Threads: %u (click for details)"
#define STR_DIAG_THREADJOBSDONE                    "   Jobs done by thread %u: %lld"
#define STR_DIAG_MOUSEPOS                          "Mouse position: %d, %d"

#define STR_FLYINGWHALES                           "(...and watch out for flying whales)"

#define STR_MENU_KEEPPLAYING                       "Keep Playing"
#define STR_MENU_QUIT                              "Quit"

#endif

